/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type PaymentMethod = {
  _id: string;
  _type: "paymentMethod";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  clerkUserId?: string;
  cardType?: "visa" | "mastercard" | "amex" | "discover" | "other";
  last4?: string;
  expiryMonth?: string;
  expiryYear?: string;
  holderName?: string;
  isDefault?: boolean;
  nickname?: string;
  stripePaymentMethodId?: string;
  billingAddress?: {
    name?: string;
    address?: string;
    city?: string;
    state?: string;
    zip?: string;
    country?: string;
  };
  isActive?: boolean;
  createdAt?: string;
  updatedAt?: string;
};

export type Address = {
  _id: string;
  _type: "address";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email?: string;
  address?: string;
  city?: string;
  state?: string;
  zip?: string;
  default?: boolean;
  createdAt?: string;
};

export type Blogcategory = {
  _id: string;
  _type: "blogcategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type Blog = {
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "author";
  };
  mainImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  blogcategories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "blogcategory";
  }>;
  publishedAt?: string;
  isLatest?: boolean;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
    listItem?: "bullet";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Banner = {
  _id: string;
  _type: "banner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  badge?: string;
  discountAmount?: number;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Order = {
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  invoice?: {
    id?: string;
    number?: string;
    hosted_invoice_url?: string;
  };
  stripeCheckoutSessionId?: string;
  stripeCustomerId?: string;
  clerkUserId?: string;
  customerName?: string;
  email?: string;
  stripePaymentIntentId?: string;
  products?: Array<{
    product?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "product";
    };
    quantity?: number;
    _key: string;
  }>;
  totalPrice?: number;
  currency?: string;
  amountDiscount?: number;
  address?: {
    state?: string;
    zip?: string;
    city?: string;
    address?: string;
    name?: string;
  };
  status?: "pending" | "processing" | "paid" | "shipped" | "out_for_delivery" | "delivered" | "cancelled";
  orderDate?: string;
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  asin?: string;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  videoUrl?: string;
  shortDescription?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
    listItem?: "bullet";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  specifications?: Array<{
    attribute?: string;
    value?: string;
    _key: string;
  }>;
  keyFeatures?: Array<string>;
  aboutThisItem?: Array<string>;
  price?: number;
  salePrice?: number;
  costPrice?: number;
  discount?: number;
  stock?: number;
  lowStockThreshold?: number;
  trackInventory?: boolean;
  categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
  brand?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "brand";
  };
  tags?: Array<string>;
  productSegments?: Array<string>;
  status?: "draft" | "active" | "inactive" | "discontinued" | "out-of-stock";
  visibility?: "public" | "hidden" | "members-only";
  zamzamChoice?: boolean;
  zamzamPlusEligible?: boolean;
  freeShipping?: boolean;
  deliveryTime?: "same-day" | "next-day" | "2-3-days" | "3-5-days" | "5-7-days" | "1-2-weeks";
  averageRating?: number;
  totalReviews?: number;
  ratingBreakdown?: {
    five?: number;
    four?: number;
    three?: number;
    two?: number;
    one?: number;
  };
  hasVariants?: boolean;
  variants?: Array<{
    name?: string;
    slug?: Slug;
    price?: number;
    stock?: number;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    attributes?: Array<{
      name?: string;
      value?: string;
      _key: string;
    }>;
    _key: string;
  }>;
  seoTitle?: string;
  seoDescription?: string;
  seoKeywords?: Array<string>;
  launchDate?: string;
  salesCount?: number;
  viewCount?: number;
  variant?: "gadget" | "appliances" | "refrigerators" | "others";
  isFeatured?: boolean;
};

export type Brand = {
  _id: string;
  _type: "brand";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  brandCode?: string;
  status?: "active" | "inactive" | "pending" | "discontinued";
  shortDescription?: string;
  fullDescription?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  tagline?: string;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  logoVariants?: Array<{
    variant?: "primary" | "secondary" | "dark" | "light" | "horizontal" | "vertical" | "icon";
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    _key: string;
  }>;
  brandColors?: Array<{
    name?: string;
    hex?: string;
    rgb?: string;
    usage?: string;
    _key: string;
  }>;
  foundedYear?: number;
  founder?: string;
  headquarters?: {
    city?: string;
    state?: string;
    country?: string;
  };
  categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
  targetAudience?: Array<string>;
  contactInfo?: {
    website?: string;
    email?: string;
    phone?: string;
    address?: string;
  };
  socialMedia?: {
    instagram?: string;
    facebook?: string;
    twitter?: string;
    linkedin?: string;
    youtube?: string;
    tiktok?: string;
  };
  tier?: "luxury" | "mid-range" | "budget" | "mass-market";
  popularity?: number;
  marketShare?: number;
  seo?: {
    metaTitle?: string;
    metaDescription?: string;
    keywords?: Array<string>;
  };
  featuredBrand?: boolean;
  displayOrder?: number;
  partnerships?: Array<{
    partner?: string;
    type?: "collaboration" | "sponsorship" | "joint-venture" | "licensing";
    description?: string;
    _key: string;
  }>;
  certifications?: Array<{
    name?: string;
    issuedBy?: string;
    year?: number;
    description?: string;
    _key: string;
  }>;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  range?: number;
  featured?: boolean;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
  listItem?: "bullet";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
  };
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: "image";
  _key: string;
}>;

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes = PaymentMethod | Address | Blogcategory | Blog | Author | Banner | Order | Product | Brand | Category | BlockContent | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityImageAsset | SanityImageMetadata | Geopoint | Slug | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./app/(client)/success/page.tsx
// Variable: query
// Query: *[_type == 'order' && clerkUserId == $userId] | order(orderData desc){  ...,products[]{    ...,product->  }}
export type QueryResult = Array<{
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  invoice?: {
    id?: string;
    number?: string;
    hosted_invoice_url?: string;
  };
  stripeCheckoutSessionId?: string;
  stripeCustomerId?: string;
  clerkUserId?: string;
  customerName?: string;
  email?: string;
  stripePaymentIntentId?: string;
  products: Array<{
    product: {
      _id: string;
      _type: "product";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      name?: string;
      slug?: Slug;
      asin?: string;
      images?: Array<{
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }>;
      videoUrl?: string;
      shortDescription?: string;
      description?: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      } | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }>;
      specifications?: Array<{
        attribute?: string;
        value?: string;
        _key: string;
      }>;
      keyFeatures?: Array<string>;
      aboutThisItem?: Array<string>;
      price?: number;
      salePrice?: number;
      costPrice?: number;
      discount?: number;
      stock?: number;
      lowStockThreshold?: number;
      trackInventory?: boolean;
      categories?: Array<{
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        _key: string;
        [internalGroqTypeReferenceTo]?: "category";
      }>;
      brand?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "brand";
      };
      tags?: Array<string>;
      productSegments?: Array<string>;
      status?: "active" | "discontinued" | "draft" | "inactive" | "out-of-stock";
      visibility?: "hidden" | "members-only" | "public";
      zamzamChoice?: boolean;
      zamzamPlusEligible?: boolean;
      freeShipping?: boolean;
      deliveryTime?: "1-2-weeks" | "2-3-days" | "3-5-days" | "5-7-days" | "next-day" | "same-day";
      averageRating?: number;
      totalReviews?: number;
      ratingBreakdown?: {
        five?: number;
        four?: number;
        three?: number;
        two?: number;
        one?: number;
      };
      hasVariants?: boolean;
      variants?: Array<{
        name?: string;
        slug?: Slug;
        price?: number;
        stock?: number;
        image?: {
          asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          };
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        attributes?: Array<{
          name?: string;
          value?: string;
          _key: string;
        }>;
        _key: string;
      }>;
      seoTitle?: string;
      seoDescription?: string;
      seoKeywords?: Array<string>;
      launchDate?: string;
      salesCount?: number;
      viewCount?: number;
      variant?: "appliances" | "gadget" | "others" | "refrigerators";
      isFeatured?: boolean;
    } | null;
    quantity?: number;
    _key: string;
  }> | null;
  totalPrice?: number;
  currency?: string;
  amountDiscount?: number;
  address?: {
    state?: string;
    zip?: string;
    city?: string;
    address?: string;
    name?: string;
  };
  status?: "cancelled" | "delivered" | "out_for_delivery" | "paid" | "pending" | "processing" | "shipped";
  orderDate?: string;
}>;

// Source: ./sanity/queries/query.ts
// Variable: BANNER_QUERY
// Query: *[_type == 'banner'] | order(publishedAt desc)
export type BANNER_QUERYResult = Array<{
  _id: string;
  _type: "banner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  badge?: string;
  discountAmount?: number;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
}>;
// Variable: FEATURED_CATEGORY_QUERY
// Query: *[_type == 'category' && featured == true] | order(name desc)
export type FEATURED_CATEGORY_QUERYResult = Array<{
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  range?: number;
  featured?: boolean;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
}>;
// Variable: ALL_PRODUCTS_QUERY
// Query: *[_type=="product" && status in ["new", "hot", "sale", "active"]] | order(name asc){  ...,  productSegments,  "categories": categories[]->title,  "brand": brand->name}
export type ALL_PRODUCTS_QUERYResult = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  asin?: string;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  videoUrl?: string;
  shortDescription?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
    listItem?: "bullet";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  specifications?: Array<{
    attribute?: string;
    value?: string;
    _key: string;
  }>;
  keyFeatures?: Array<string>;
  aboutThisItem?: Array<string>;
  price?: number;
  salePrice?: number;
  costPrice?: number;
  discount?: number;
  stock?: number;
  lowStockThreshold?: number;
  trackInventory?: boolean;
  categories: Array<string | null> | null;
  brand: null;
  tags?: Array<string>;
  productSegments: Array<string> | null;
  status?: "active" | "discontinued" | "draft" | "inactive" | "out-of-stock";
  visibility?: "hidden" | "members-only" | "public";
  zamzamChoice?: boolean;
  zamzamPlusEligible?: boolean;
  freeShipping?: boolean;
  deliveryTime?: "1-2-weeks" | "2-3-days" | "3-5-days" | "5-7-days" | "next-day" | "same-day";
  averageRating?: number;
  totalReviews?: number;
  ratingBreakdown?: {
    five?: number;
    four?: number;
    three?: number;
    two?: number;
    one?: number;
  };
  hasVariants?: boolean;
  variants?: Array<{
    name?: string;
    slug?: Slug;
    price?: number;
    stock?: number;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    attributes?: Array<{
      name?: string;
      value?: string;
      _key: string;
    }>;
    _key: string;
  }>;
  seoTitle?: string;
  seoDescription?: string;
  seoKeywords?: Array<string>;
  launchDate?: string;
  salesCount?: number;
  viewCount?: number;
  variant?: "appliances" | "gadget" | "others" | "refrigerators";
  isFeatured?: boolean;
}>;
// Variable: NEW_ARRIVAL_PRODUCTS
// Query: *[_type == 'product' && status == "active" && "new-arrival" in productSegments] | order(_createdAt desc){  ...,  "categories": categories[]->title,  "brand": brand->name}
export type NEW_ARRIVAL_PRODUCTSResult = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  asin?: string;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  videoUrl?: string;
  shortDescription?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
    listItem?: "bullet";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  specifications?: Array<{
    attribute?: string;
    value?: string;
    _key: string;
  }>;
  keyFeatures?: Array<string>;
  aboutThisItem?: Array<string>;
  price?: number;
  salePrice?: number;
  costPrice?: number;
  discount?: number;
  stock?: number;
  lowStockThreshold?: number;
  trackInventory?: boolean;
  categories: Array<string | null> | null;
  brand: null;
  tags?: Array<string>;
  productSegments?: Array<string>;
  status?: "active" | "discontinued" | "draft" | "inactive" | "out-of-stock";
  visibility?: "hidden" | "members-only" | "public";
  zamzamChoice?: boolean;
  zamzamPlusEligible?: boolean;
  freeShipping?: boolean;
  deliveryTime?: "1-2-weeks" | "2-3-days" | "3-5-days" | "5-7-days" | "next-day" | "same-day";
  averageRating?: number;
  totalReviews?: number;
  ratingBreakdown?: {
    five?: number;
    four?: number;
    three?: number;
    two?: number;
    one?: number;
  };
  hasVariants?: boolean;
  variants?: Array<{
    name?: string;
    slug?: Slug;
    price?: number;
    stock?: number;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    attributes?: Array<{
      name?: string;
      value?: string;
      _key: string;
    }>;
    _key: string;
  }>;
  seoTitle?: string;
  seoDescription?: string;
  seoKeywords?: Array<string>;
  launchDate?: string;
  salesCount?: number;
  viewCount?: number;
  variant?: "appliances" | "gadget" | "others" | "refrigerators";
  isFeatured?: boolean;
}>;
// Variable: BEST_SELLER_PRODUCTS
// Query: *[_type == 'product' && status == "active" && "best-seller" in productSegments] | order(salesCount desc){  ...,  "categories": categories[]->title,  "brand": brand->name}
export type BEST_SELLER_PRODUCTSResult = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  asin?: string;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  videoUrl?: string;
  shortDescription?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
    listItem?: "bullet";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  specifications?: Array<{
    attribute?: string;
    value?: string;
    _key: string;
  }>;
  keyFeatures?: Array<string>;
  aboutThisItem?: Array<string>;
  price?: number;
  salePrice?: number;
  costPrice?: number;
  discount?: number;
  stock?: number;
  lowStockThreshold?: number;
  trackInventory?: boolean;
  categories: Array<string | null> | null;
  brand: null;
  tags?: Array<string>;
  productSegments?: Array<string>;
  status?: "active" | "discontinued" | "draft" | "inactive" | "out-of-stock";
  visibility?: "hidden" | "members-only" | "public";
  zamzamChoice?: boolean;
  zamzamPlusEligible?: boolean;
  freeShipping?: boolean;
  deliveryTime?: "1-2-weeks" | "2-3-days" | "3-5-days" | "5-7-days" | "next-day" | "same-day";
  averageRating?: number;
  totalReviews?: number;
  ratingBreakdown?: {
    five?: number;
    four?: number;
    three?: number;
    two?: number;
    one?: number;
  };
  hasVariants?: boolean;
  variants?: Array<{
    name?: string;
    slug?: Slug;
    price?: number;
    stock?: number;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    attributes?: Array<{
      name?: string;
      value?: string;
      _key: string;
    }>;
    _key: string;
  }>;
  seoTitle?: string;
  seoDescription?: string;
  seoKeywords?: Array<string>;
  launchDate?: string;
  salesCount?: number;
  viewCount?: number;
  variant?: "appliances" | "gadget" | "others" | "refrigerators";
  isFeatured?: boolean;
}>;
// Variable: FEATURED_PRODUCTS
// Query: *[_type == 'product' && status == "active" && "featured" in productSegments] | order(name asc){  ...,  "categories": categories[]->title,  "brand": brand->name}
export type FEATURED_PRODUCTSResult = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  asin?: string;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  videoUrl?: string;
  shortDescription?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
    listItem?: "bullet";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  specifications?: Array<{
    attribute?: string;
    value?: string;
    _key: string;
  }>;
  keyFeatures?: Array<string>;
  aboutThisItem?: Array<string>;
  price?: number;
  salePrice?: number;
  costPrice?: number;
  discount?: number;
  stock?: number;
  lowStockThreshold?: number;
  trackInventory?: boolean;
  categories: Array<string | null> | null;
  brand: null;
  tags?: Array<string>;
  productSegments?: Array<string>;
  status?: "active" | "discontinued" | "draft" | "inactive" | "out-of-stock";
  visibility?: "hidden" | "members-only" | "public";
  zamzamChoice?: boolean;
  zamzamPlusEligible?: boolean;
  freeShipping?: boolean;
  deliveryTime?: "1-2-weeks" | "2-3-days" | "3-5-days" | "5-7-days" | "next-day" | "same-day";
  averageRating?: number;
  totalReviews?: number;
  ratingBreakdown?: {
    five?: number;
    four?: number;
    three?: number;
    two?: number;
    one?: number;
  };
  hasVariants?: boolean;
  variants?: Array<{
    name?: string;
    slug?: Slug;
    price?: number;
    stock?: number;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    attributes?: Array<{
      name?: string;
      value?: string;
      _key: string;
    }>;
    _key: string;
  }>;
  seoTitle?: string;
  seoDescription?: string;
  seoKeywords?: Array<string>;
  launchDate?: string;
  salesCount?: number;
  viewCount?: number;
  variant?: "appliances" | "gadget" | "others" | "refrigerators";
  isFeatured?: boolean;
}>;
// Variable: SPECIAL_OFFER_PRODUCTS
// Query: *[_type == 'product' && status == "active" && "special-offer" in productSegments] | order(discount desc){  ...,  "categories": categories[]->title,  "brand": brand->name}
export type SPECIAL_OFFER_PRODUCTSResult = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  asin?: string;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  videoUrl?: string;
  shortDescription?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
    listItem?: "bullet";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  specifications?: Array<{
    attribute?: string;
    value?: string;
    _key: string;
  }>;
  keyFeatures?: Array<string>;
  aboutThisItem?: Array<string>;
  price?: number;
  salePrice?: number;
  costPrice?: number;
  discount?: number;
  stock?: number;
  lowStockThreshold?: number;
  trackInventory?: boolean;
  categories: Array<string | null> | null;
  brand: null;
  tags?: Array<string>;
  productSegments?: Array<string>;
  status?: "active" | "discontinued" | "draft" | "inactive" | "out-of-stock";
  visibility?: "hidden" | "members-only" | "public";
  zamzamChoice?: boolean;
  zamzamPlusEligible?: boolean;
  freeShipping?: boolean;
  deliveryTime?: "1-2-weeks" | "2-3-days" | "3-5-days" | "5-7-days" | "next-day" | "same-day";
  averageRating?: number;
  totalReviews?: number;
  ratingBreakdown?: {
    five?: number;
    four?: number;
    three?: number;
    two?: number;
    one?: number;
  };
  hasVariants?: boolean;
  variants?: Array<{
    name?: string;
    slug?: Slug;
    price?: number;
    stock?: number;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    attributes?: Array<{
      name?: string;
      value?: string;
      _key: string;
    }>;
    _key: string;
  }>;
  seoTitle?: string;
  seoDescription?: string;
  seoKeywords?: Array<string>;
  launchDate?: string;
  salesCount?: number;
  viewCount?: number;
  variant?: "appliances" | "gadget" | "others" | "refrigerators";
  isFeatured?: boolean;
}>;
// Variable: PRODUCTS_BY_SEGMENT
// Query: *[_type == 'product' && status == "active" && $segment in productSegments] | order(name asc){  ...,  "categories": categories[]->title,  "brand": brand->name}
export type PRODUCTS_BY_SEGMENTResult = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  asin?: string;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  videoUrl?: string;
  shortDescription?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
    listItem?: "bullet";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  specifications?: Array<{
    attribute?: string;
    value?: string;
    _key: string;
  }>;
  keyFeatures?: Array<string>;
  aboutThisItem?: Array<string>;
  price?: number;
  salePrice?: number;
  costPrice?: number;
  discount?: number;
  stock?: number;
  lowStockThreshold?: number;
  trackInventory?: boolean;
  categories: Array<string | null> | null;
  brand: null;
  tags?: Array<string>;
  productSegments?: Array<string>;
  status?: "active" | "discontinued" | "draft" | "inactive" | "out-of-stock";
  visibility?: "hidden" | "members-only" | "public";
  zamzamChoice?: boolean;
  zamzamPlusEligible?: boolean;
  freeShipping?: boolean;
  deliveryTime?: "1-2-weeks" | "2-3-days" | "3-5-days" | "5-7-days" | "next-day" | "same-day";
  averageRating?: number;
  totalReviews?: number;
  ratingBreakdown?: {
    five?: number;
    four?: number;
    three?: number;
    two?: number;
    one?: number;
  };
  hasVariants?: boolean;
  variants?: Array<{
    name?: string;
    slug?: Slug;
    price?: number;
    stock?: number;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    attributes?: Array<{
      name?: string;
      value?: string;
      _key: string;
    }>;
    _key: string;
  }>;
  seoTitle?: string;
  seoDescription?: string;
  seoKeywords?: Array<string>;
  launchDate?: string;
  salesCount?: number;
  viewCount?: number;
  variant?: "appliances" | "gadget" | "others" | "refrigerators";
  isFeatured?: boolean;
}>;
// Variable: ALL_PRODUCTS_WITH_SEGMENTS
// Query: *[_type == 'product' && status == "active"] | order(_createdAt desc){  ...,  "categories": categories[]->title,  "brand": brand->name}
export type ALL_PRODUCTS_WITH_SEGMENTSResult = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  asin?: string;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  videoUrl?: string;
  shortDescription?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
    listItem?: "bullet";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  specifications?: Array<{
    attribute?: string;
    value?: string;
    _key: string;
  }>;
  keyFeatures?: Array<string>;
  aboutThisItem?: Array<string>;
  price?: number;
  salePrice?: number;
  costPrice?: number;
  discount?: number;
  stock?: number;
  lowStockThreshold?: number;
  trackInventory?: boolean;
  categories: Array<string | null> | null;
  brand: null;
  tags?: Array<string>;
  productSegments?: Array<string>;
  status?: "active" | "discontinued" | "draft" | "inactive" | "out-of-stock";
  visibility?: "hidden" | "members-only" | "public";
  zamzamChoice?: boolean;
  zamzamPlusEligible?: boolean;
  freeShipping?: boolean;
  deliveryTime?: "1-2-weeks" | "2-3-days" | "3-5-days" | "5-7-days" | "next-day" | "same-day";
  averageRating?: number;
  totalReviews?: number;
  ratingBreakdown?: {
    five?: number;
    four?: number;
    three?: number;
    two?: number;
    one?: number;
  };
  hasVariants?: boolean;
  variants?: Array<{
    name?: string;
    slug?: Slug;
    price?: number;
    stock?: number;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    attributes?: Array<{
      name?: string;
      value?: string;
      _key: string;
    }>;
    _key: string;
  }>;
  seoTitle?: string;
  seoDescription?: string;
  seoKeywords?: Array<string>;
  launchDate?: string;
  salesCount?: number;
  viewCount?: number;
  variant?: "appliances" | "gadget" | "others" | "refrigerators";
  isFeatured?: boolean;
}>;
// Variable: DEAL_PRODUCTS
// Query: *[_type == 'product' && status == 'hot'] | order(name asc){  ...,"categories": categories[]->title}
export type DEAL_PRODUCTSResult = Array<never>;
// Variable: FEATURE_PRODUCTS
// Query: *[_type == 'product' && isFeatured == true] | order(name asc){  ...,"categories": categories[]->title}
export type FEATURE_PRODUCTSResult = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  asin?: string;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  videoUrl?: string;
  shortDescription?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
    listItem?: "bullet";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  specifications?: Array<{
    attribute?: string;
    value?: string;
    _key: string;
  }>;
  keyFeatures?: Array<string>;
  aboutThisItem?: Array<string>;
  price?: number;
  salePrice?: number;
  costPrice?: number;
  discount?: number;
  stock?: number;
  lowStockThreshold?: number;
  trackInventory?: boolean;
  categories: Array<string | null> | null;
  brand?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "brand";
  };
  tags?: Array<string>;
  productSegments?: Array<string>;
  status?: "active" | "discontinued" | "draft" | "inactive" | "out-of-stock";
  visibility?: "hidden" | "members-only" | "public";
  zamzamChoice?: boolean;
  zamzamPlusEligible?: boolean;
  freeShipping?: boolean;
  deliveryTime?: "1-2-weeks" | "2-3-days" | "3-5-days" | "5-7-days" | "next-day" | "same-day";
  averageRating?: number;
  totalReviews?: number;
  ratingBreakdown?: {
    five?: number;
    four?: number;
    three?: number;
    two?: number;
    one?: number;
  };
  hasVariants?: boolean;
  variants?: Array<{
    name?: string;
    slug?: Slug;
    price?: number;
    stock?: number;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    attributes?: Array<{
      name?: string;
      value?: string;
      _key: string;
    }>;
    _key: string;
  }>;
  seoTitle?: string;
  seoDescription?: string;
  seoKeywords?: Array<string>;
  launchDate?: string;
  salesCount?: number;
  viewCount?: number;
  variant?: "appliances" | "gadget" | "others" | "refrigerators";
  isFeatured?: boolean;
}>;
// Variable: BRANDS_QUERY
// Query: *[_type=='brand'] | order(name asc)
export type BRANDS_QUERYResult = Array<{
  _id: string;
  _type: "brand";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  brandCode?: string;
  status?: "active" | "discontinued" | "inactive" | "pending";
  shortDescription?: string;
  fullDescription?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  tagline?: string;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  logoVariants?: Array<{
    variant?: "dark" | "horizontal" | "icon" | "light" | "primary" | "secondary" | "vertical";
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    _key: string;
  }>;
  brandColors?: Array<{
    name?: string;
    hex?: string;
    rgb?: string;
    usage?: string;
    _key: string;
  }>;
  foundedYear?: number;
  founder?: string;
  headquarters?: {
    city?: string;
    state?: string;
    country?: string;
  };
  categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
  targetAudience?: Array<string>;
  contactInfo?: {
    website?: string;
    email?: string;
    phone?: string;
    address?: string;
  };
  socialMedia?: {
    instagram?: string;
    facebook?: string;
    twitter?: string;
    linkedin?: string;
    youtube?: string;
    tiktok?: string;
  };
  tier?: "budget" | "luxury" | "mass-market" | "mid-range";
  popularity?: number;
  marketShare?: number;
  seo?: {
    metaTitle?: string;
    metaDescription?: string;
    keywords?: Array<string>;
  };
  featuredBrand?: boolean;
  displayOrder?: number;
  partnerships?: Array<{
    partner?: string;
    type?: "collaboration" | "joint-venture" | "licensing" | "sponsorship";
    description?: string;
    _key: string;
  }>;
  certifications?: Array<{
    name?: string;
    issuedBy?: string;
    year?: number;
    description?: string;
    _key: string;
  }>;
}>;
// Variable: LATEST_BLOG_QUERY
// Query: *[_type == 'blog' && isLatest == true]|order(name asc){    ...,    blogcategories[]->{    title  }  }
export type LATEST_BLOG_QUERYResult = Array<{
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "author";
  };
  mainImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  blogcategories: Array<{
    title: string | null;
  }> | null;
  publishedAt?: string;
  isLatest?: boolean;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
    listItem?: "bullet";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
}>;
// Variable: GET_ALL_BLOG
// Query: *[_type == 'blog'] | order(publishedAt desc)[0...$quantity]{  ...,       blogcategories[]->{    title}    }
export type GET_ALL_BLOGResult = Array<{
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "author";
  };
  mainImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  blogcategories: Array<{
    title: string | null;
  }> | null;
  publishedAt?: string;
  isLatest?: boolean;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
    listItem?: "bullet";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
}>;
// Variable: SINGLE_BLOG_QUERY
// Query: *[_type == "blog" && slug.current == $slug][0]{  ...,     author->{    name,    image,  },  blogcategories[]->{    title,    "slug": slug.current,  },}
export type SINGLE_BLOG_QUERYResult = {
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author: {
    name: string | null;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  mainImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  blogcategories: Array<{
    title: string | null;
    slug: string | null;
  }> | null;
  publishedAt?: string;
  isLatest?: boolean;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
    listItem?: "bullet";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
} | null;
// Variable: BLOG_CATEGORIES
// Query: *[_type == "blog"]{     blogcategories[]->{    ...    }  }
export type BLOG_CATEGORIESResult = Array<{
  blogcategories: Array<{
    _id: string;
    _type: "blogcategory";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    slug?: Slug;
    description?: string;
  }> | null;
}>;
// Variable: OTHERS_BLOG_QUERY
// Query: *[  _type == "blog"  && defined(slug.current)  && slug.current != $slug]|order(publishedAt desc)[0...$quantity]{...  publishedAt,  title,  mainImage,  slug,  author->{    name,    image,  },  categories[]->{    title,    "slug": slug.current,  }}
export type OTHERS_BLOG_QUERYResult = Array<{
  title: string | null;
  mainImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  slug: Slug | null;
  author: {
    name: string | null;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  categories: null;
}>;
// Variable: ADDRESS_QUERY
// Query: *[_type=="address"] | order(publishedAt desc)
export type ADDRESS_QUERYResult = Array<{
  _id: string;
  _type: "address";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email?: string;
  address?: string;
  city?: string;
  state?: string;
  zip?: string;
  default?: boolean;
  createdAt?: string;
}>;
// Variable: ALLCATEGORIES_QUERY
// Query: *[_type == 'category'] | order(name asc) [0...$quantity]
export type ALLCATEGORIES_QUERYResult = Array<{
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  range?: number;
  featured?: boolean;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
}>;
// Variable: PRODUCT_BY_SLUG_QUERY
// Query: *[_type == "product" && slug.current == $slug] | order(name asc) [0]{    _id,    name,    slug,    shortDescription,    description,    images,    price,    salePrice,    discount,    stock,    lowStockThreshold,    asin,    aboutThisItem,    keyFeatures,    specifications,    zamzamChoice,    zamzamPlusEligible,    freeShipping,    deliveryTime,    averageRating,    totalReviews,    productSegments,    categories[]->{title, slug},    brand->{title, logo, shortDescription},    variants,    "relatedProducts": *[_type == "product" && references(^.categories[]._ref) && _id != ^._id][0...4]{      _id,      name,      slug,      images,      price,      salePrice,      averageRating    }  }
export type PRODUCT_BY_SLUG_QUERYResult = {
  _id: string;
  name: string | null;
  slug: Slug | null;
  shortDescription: string | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
    listItem?: "bullet";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }> | null;
  images: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }> | null;
  price: number | null;
  salePrice: number | null;
  discount: number | null;
  stock: number | null;
  lowStockThreshold: number | null;
  asin: string | null;
  aboutThisItem: Array<string> | null;
  keyFeatures: Array<string> | null;
  specifications: Array<{
    attribute?: string;
    value?: string;
    _key: string;
  }> | null;
  zamzamChoice: boolean | null;
  zamzamPlusEligible: boolean | null;
  freeShipping: boolean | null;
  deliveryTime: "1-2-weeks" | "2-3-days" | "3-5-days" | "5-7-days" | "next-day" | "same-day" | null;
  averageRating: number | null;
  totalReviews: number | null;
  productSegments: Array<string> | null;
  categories: Array<{
    title: string | null;
    slug: Slug | null;
  }> | null;
  brand: {
    title: string | null;
    logo: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    shortDescription: string | null;
  } | null;
  variants: Array<{
    name?: string;
    slug?: Slug;
    price?: number;
    stock?: number;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    attributes?: Array<{
      name?: string;
      value?: string;
      _key: string;
    }>;
    _key: string;
  }> | null;
  relatedProducts: Array<{
    _id: string;
    name: string | null;
    slug: Slug | null;
    images: Array<{
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }> | null;
    price: number | null;
    salePrice: number | null;
    averageRating: number | null;
  }>;
} | null;
// Variable: BRAND_QUERY
// Query: *[_type == "product" && slug.current == $slug]{"brandName": brand->title}
export type BRAND_QUERYResult = Array<{
  brandName: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == 'order' && clerkUserId == $userId] | order(orderData desc){\n  ...,products[]{\n    ...,product->\n  }\n}": QueryResult;
    "*[_type == 'banner'] | order(publishedAt desc)": BANNER_QUERYResult;
    "*[_type == 'category' && featured == true] | order(name desc)": FEATURED_CATEGORY_QUERYResult;
    "*[_type==\"product\" && status in [\"new\", \"hot\", \"sale\", \"active\"]] | order(name asc){\n  ...,\n  productSegments,\n  \"categories\": categories[]->title,\n  \"brand\": brand->name\n}": ALL_PRODUCTS_QUERYResult;
    "*[_type == 'product' && status == \"active\" && \"new-arrival\" in productSegments] | order(_createdAt desc){\n  ...,\n  \"categories\": categories[]->title,\n  \"brand\": brand->name\n}": NEW_ARRIVAL_PRODUCTSResult;
    "*[_type == 'product' && status == \"active\" && \"best-seller\" in productSegments] | order(salesCount desc){\n  ...,\n  \"categories\": categories[]->title,\n  \"brand\": brand->name\n}": BEST_SELLER_PRODUCTSResult;
    "*[_type == 'product' && status == \"active\" && \"featured\" in productSegments] | order(name asc){\n  ...,\n  \"categories\": categories[]->title,\n  \"brand\": brand->name\n}": FEATURED_PRODUCTSResult;
    "*[_type == 'product' && status == \"active\" && \"special-offer\" in productSegments] | order(discount desc){\n  ...,\n  \"categories\": categories[]->title,\n  \"brand\": brand->name\n}": SPECIAL_OFFER_PRODUCTSResult;
    "*[_type == 'product' && status == \"active\" && $segment in productSegments] | order(name asc){\n  ...,\n  \"categories\": categories[]->title,\n  \"brand\": brand->name\n}": PRODUCTS_BY_SEGMENTResult;
    "*[_type == 'product' && status == \"active\"] | order(_createdAt desc){\n  ...,\n  \"categories\": categories[]->title,\n  \"brand\": brand->name\n}": ALL_PRODUCTS_WITH_SEGMENTSResult;
    "*[_type == 'product' && status == 'hot'] | order(name asc){\n  ...,\"categories\": categories[]->title\n}": DEAL_PRODUCTSResult;
    "*[_type == 'product' && isFeatured == true] | order(name asc){\n  ...,\"categories\": categories[]->title\n}": FEATURE_PRODUCTSResult;
    "*[_type=='brand'] | order(name asc) ": BRANDS_QUERYResult;
    " *[_type == 'blog' && isLatest == true]|order(name asc){\n    ...,\n    blogcategories[]->{\n    title\n  }\n  }": LATEST_BLOG_QUERYResult;
    "*[_type == 'blog'] | order(publishedAt desc)[0...$quantity]{\n  ...,  \n     blogcategories[]->{\n    title\n}\n    }\n  ": GET_ALL_BLOGResult;
    "*[_type == \"blog\" && slug.current == $slug][0]{\n  ..., \n    author->{\n    name,\n    image,\n  },\n  blogcategories[]->{\n    title,\n    \"slug\": slug.current,\n  },\n}": SINGLE_BLOG_QUERYResult;
    "*[_type == \"blog\"]{\n     blogcategories[]->{\n    ...\n    }\n  }": BLOG_CATEGORIESResult;
    "*[\n  _type == \"blog\"\n  && defined(slug.current)\n  && slug.current != $slug\n]|order(publishedAt desc)[0...$quantity]{\n...\n  publishedAt,\n  title,\n  mainImage,\n  slug,\n  author->{\n    name,\n    image,\n  },\n  categories[]->{\n    title,\n    \"slug\": slug.current,\n  }\n}": OTHERS_BLOG_QUERYResult;
    "*[_type==\"address\"] | order(publishedAt desc)": ADDRESS_QUERYResult;
    "*[_type == 'category'] | order(name asc) [0...$quantity]": ALLCATEGORIES_QUERYResult;
    "*[_type == \"product\" && slug.current == $slug] | order(name asc) [0]{\n    _id,\n    name,\n    slug,\n    shortDescription,\n    description,\n    images,\n    price,\n    salePrice,\n    discount,\n    stock,\n    lowStockThreshold,\n    asin,\n    aboutThisItem,\n    keyFeatures,\n    specifications,\n    zamzamChoice,\n    zamzamPlusEligible,\n    freeShipping,\n    deliveryTime,\n    averageRating,\n    totalReviews,\n    productSegments,\n    categories[]->{title, slug},\n    brand->{title, logo, shortDescription},\n    variants,\n    \"relatedProducts\": *[_type == \"product\" && references(^.categories[]._ref) && _id != ^._id][0...4]{\n      _id,\n      name,\n      slug,\n      images,\n      price,\n      salePrice,\n      averageRating\n    }\n  }": PRODUCT_BY_SLUG_QUERYResult;
    "*[_type == \"product\" && slug.current == $slug]{\n\"brandName\": brand->title\n}": BRAND_QUERYResult;
  }
}
